### PR TITLE
Generalize DI using AnnotatedFunction

### PR DESCRIPTION
**Pull request by ludovicc**
Solves #25

### CODE REVIEW

**Comment by jokade** [comment]
@ludovicc Great work!
Could you please give me a short summary of the changes regarding `AnnotatedFunction` along with some use cases (so that I can update the README)? 

On a side note, I have redesigned the directive API, since using a scala classes for directive controllers doesn't work out (the controller instance is created by Angular). I would be glad if you could give me your opinion on this -- the changes are located in the `issue28` branch.

I hope that we can publish a 0.2 release within the week.

**Comment by jokade** [comment]
I have one minor concern regarding your refactoring: a value named `angular` within the package object `angular` could result in confusing compiler errors, if one imports `biz.enef.angular` instead of `biz.enef.angular._`. Maybe we should rename the `Angular` trait to `NG`and then use `Angular` as the name of the value in the package object? Another option would be to rename the entire package to `ng` (but that's a quite extensive change for such a minor issue).

**Comment by ludovicc** [comment]
Hi,

Good pick!
I would rename the whole package to 'angulate', since that's the name of
the library.

Otherwise, rename the angular value to 'ng'.

Ludovic

**Comment by ludovicc** [comment]
On 15/02/2015 13:18, jokade wrote:

> @ludovicc https://github.com/ludovicc Great work!
> Could you please give me a short summary of the changes regarding
> |AnnotatedFunction| along with some use cases (so that I can update the
> README)?
> 
> On a side note, I have redesigned the directive API, since using a scala
> classes for directive controllers doesn't work out (the controller
> instance is created by Angular). I would be glad if you could give me
> your opinion on this -- the changes are located in the |issue28| branch.
> 
> I hope that we can publish a 0.2 release within the week.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jokade/scalajs-angulate/pull/31#issuecomment-74415181.

I have documented AnnotatedFunction in the Readme.

**Comment by jokade** [comment]
Sorry, I didn't notice that your changes to the Readme...
I went ahead and renamed the base package to `angulate`.

**Comment by ludovicc** [comment]
Thanks for merging. I'm still reading about directives in Angular, I'll try to have some feedback by the end of the week.

**Pull request merged**
