### PR TITLE
Add objectEquality parameter to $watch method

### PR DESCRIPTION
**Pull request by hieronx**

### CODE REVIEW

**Comment by hieronx** [comment]
See: https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch

**Comment by hieronx** [comment]
@jokade could you merge and release this PR? Thanks a lot!

**Comment by jokade** [comment]
I’m currently on a trip with poor connection… I’ll merge it this evening.

**Comment by jokade** [comment]
LGTM -- sorry it took so long...

**Comment by hieronx** [comment]
No problem, thanks!

**Pull request merged**
