### PR TITLE
Replace macros with methods on wrappers

### PR DESCRIPTION
**Pull request by ludovicc**

### CODE REVIEW

**Comment by jokade** [comment]
Great work, thanks!
I've published the 0.2-SNAPSHOT to Sonatype.

**Comment by ludovicc** [comment]
Hello,

Thanks for merging, I'll work next on improving the

https://groups.google.com/forum/#!topic/scala-js/IQLZYp-kwHA

**Comment by jokade** [comment]
Well, I've published the 0.1 for SJS 0.6.0 a few hours ago. Current problem for angulate is, that utest has not been published for SJS 0.6.0...

**Comment by ludovicc** [comment]
Hello,

Thanks for merging, I'll work next on improving the way declarative
markup is handled for functions. The idea is to wrap a js.Dictionary in
an AnyVal. The wrapper and the implicit function converting scala
functions to it will be more reusable, I'll need that for ui-router.

There's a release of sjs 0.6, but as you've noted (sorry, my mail was
sent while writing it, I don't know why, just pressed enter key...)
uTest is not yet ready for it.

https://groups.google.com/forum/#!topic/scala-js/IQLZYp-kwHA

Cheers,
Ludovic

**Comment by jokade** [comment]
That explains your first post :)
Could you give an example for "declarative markup" for functions?

Cheers,
Johannes

**Comment by ludovicc** [comment]
The correct term is 'inline array annotation', I was reading the Angular
doc too fast.

It looks like this

 ["$scope", "MyService", function($scope, MyService) {...}]

Ludovic

**Comment by jokade** [comment]
Ahh, so you want to generalize the support for function DI (as supported by `Module.run` and `Module.config`)? If so, maybe you could open an issue for this topic (for any further discussion)?

**Pull request merged**
